version: '3.8'

services:
    accounts:
      image: rafaljarosinski/accounts:0.0.3-SNAPSHOT
      container_name: accounts-ms
      ports:
          - "8091:8091"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - easybank

    loans:
      image: rafaljarosinski/cards:0.0.3-SNAPSHOT
      container_name: loans-ms
      ports:
          - "8092:8092"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - easybank

    cards:
      image: rafaljarosinski/cards:0.0.3-SNAPSHOT
      container_name: cards-ms
      ports:
        - "8093:8093"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - easybank

networks:
  easybank:
    driver: bridge