#spring:
#  config:
#    activate:
#      on-profile: prod

build:
  version: "1.0"

loans:
  message: "Welcome to the Loans related PROD API"
  contactDetails:
    name: "Jack Doe"
    email: "jack.doe@example.com"
  onCallSupport:
    - "(555) 555-5635"
    - "(555) 555-8372"