spring:
  application:
    name: loans
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  config:
    import: ${SPRING_CONFIG_IMPORT}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8092