spring:
  application:
    name: eurekaserver

  config:
    import: ${SPRING_CONFIG_IMPORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true