version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - easybank

  config_server:
    image: rafaljarosinski/configserver:0.0.3-SNAPSHOT
    container_name: config_server
    ports:
        - "8071:8071"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - easybank

  accounts:
    image: rafaljarosinski/accounts:0.0.3-SNAPSHOT
    container_name: accounts-ms
    ports:
        - "8091:8091"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - easybank
    environment:
      SPRING_APP_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://config_server:8071"
      SPRING_PROFILES_ACTIVE: qa
    depends_on:
      config_server:
        condition: service_healthy

  loans:
    image: rafaljarosinski/cards:0.0.3-SNAPSHOT
    container_name: loans-ms
    ports:
        - "8092:8092"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - easybank
    environment:
      SPRING_APP_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://config_server:8071"
      SPRING_PROFILES_ACTIVE: qa
    depends_on:
      config_server:
        condition: service_healthy

  cards:
    image: rafaljarosinski/cards:0.0.3-SNAPSHOT
    container_name: cards-ms
    ports:
      - "8093:8093"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - easybank
    environment:
      SPRING_APP_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://config_server:8071"
      SPRING_PROFILES_ACTIVE: qa
    depends_on:
      config_server:
        condition: service_healthy

networks:
  easybank:
    driver: bridge