build:
  version: "3.0"

accounts:
  message: "Welcome to the Accounts related local API"
  contactDetails:
    name: "John Doe"
    email: "john.doe@example.com"
  onCallSupport:
    - "(555) 555-1234"
    - "(555) 555-5678"