build:
  version: "1.0"

cards:
  message: "Welcome to the Cards related PROD API"
  contactDetails:
    name: "Jack Doe"
    email: "jack.doe@example.com"
  onCallSupport:
    - "(555) 555-5635"
    - "(555) 555-8372"