build:
  version: "3.0"

loans:
  message: "Welcome to the Loans related local API"
  contactDetails:
    name: "John Doe"
    email: "john.doe@example.com"
  onCallSupport:
    - "(555) 555-1234"
    - "(555) 555-5678"
