#spring:
#  config:
#    activate:
#      on-profile: qa

build:
  version: "2.0"

accounts:
  message: "Welcome to the Accounts related QA API"
  contactDetails:
    name: "Peter Doe"
    email: "peter.doe@example.com"
  onCallSupport:
    - "(555) 555-1234"
    - "(555) 555-5678"