services:
  network-deploy-service:
    networks:
      - easybank

  microservice-base-service:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: "700m"

  microservice-configserver-config:
    extends:
      service: microservice-base-service
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://config_server:8071"