version: '3.8'

services:
  rabbitmq:
    extends:
      file: common-config.yml
      service: network-deploy-service
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  accounts_db:
    extends:
      file: common-config.yml
      service: microservice-db-config
    container_name: accounts_db
    environment:
      MYSQL_DATABASE: accountsdb
    ports:
      - "3306:3306"
    volumes:
      - ../../data/accountsdb/conf/my.cnf:/etc/my.cnf
      - ../../data/accountsdb/data:/var/lib/mysql:rw

  loans_db:
    extends:
      file: common-config.yml
      service: microservice-db-config
    container_name: loans_db
    environment:
      MYSQL_DATABASE: loansdb
    ports:
      - "3307:3306"
    volumes:
      - ../../data/loansdb/conf/my.cnf:/etc/my.cnf
      - ../../data/loansdb/data:/var/lib/mysql:rw

  cards_db:
    extends:
      file: common-config.yml
      service: microservice-db-config
    container_name: cards_db
    environment:
      MYSQL_DATABASE: cardsdb
    ports:
      - "3308:3306"
    volumes:
      - ../../data/cardsdb/conf/my.cnf:/etc/my.cnf
      - ../../data/cardsdb/data:/var/lib/mysql:rw

  adminer:
    extends:
      file: common-config.yml
      service: network-deploy-service
    image: adminer
    container_name: adminer
    hostname: adminer
    ports:
      - "8080:8080"

  configserver:
    extends:
      file: common-config.yml
      service: microservice-base-service
    image: rafaljarosinski/configserver:0.0.3-SNAPSHOT
    container_name: configserver
    hostname: configserver
    ports:
        - "8071:8071"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      rabbitmq:
        condition: service_healthy

  accounts:
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    image: rafaljarosinski/accounts:0.0.6-SNAPSHOT
    container_name: accounts-ms
    ports:
        - "8091:8091"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: jdbc:mysql://accounts_db:3306/accountsdb
      MYSQL_DB_USER: appuser
      MYSQL_DB_PASSWORD: zaq12wsx
    depends_on:
      configserver:
        condition: service_healthy
      accounts_db:
        condition: service_healthy

  loans:
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    image: rafaljarosinski/loans:0.0.6-SNAPSHOT
    container_name: loans-ms
    ports:
        - "8092:8092"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: jdbc:mysql://loans_db:3306/loansdb
      MYSQL_DB_USER: appuser
      MYSQL_DB_PASSWORD: zaq12wsx
    depends_on:
      configserver:
        condition: service_healthy
      loans_db:
        condition: service_healthy

  cards:
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    image: rafaljarosinski/cards:0.0.6-SNAPSHOT
    container_name: cards-ms
    ports:
      - "8093:8093"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: jdbc:mysql://cards_db:3306/cardsdb
      MYSQL_DB_USER: appuser
      MYSQL_DB_PASSWORD: zaq12wsx
    depends_on:
      configserver:
        condition: service_healthy
      cards_db:
        condition: service_healthy

networks:
  easybank:
    driver: bridge

#volumes:
#  accountsDB:
#    driver: local
#  loansDB:
#    driver: local
#  cardsDB:
#    driver: local