logging:
  level:
    org.springframework.cloud: TRACE

spring:
  application:
    name: "configserver"

  profiles:
#    active: native
    active: git


  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/config
#          search-locations: "file:///home//galthran//app-config"
        git:
          uri: https://github.com/galthran/eazybytes-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key-store:
    location: keystore.jks
    secret: secret
    password: password
    type: jks
    alias: eazybytes

# key: "APODNU3093r2rbjzxcn09u213asdhy08WRFH"

server:
  port: 8071
